### ISSUE TITLE
Invalid Instruction Fetch while fuzzing a monolithic firmware.

### ISSUE THREAD

**Issue by PwnVerse** [MultiFuzz/MultiFuzz#2]
## The issue

I've been trying to setup fuzzing on a compiled firmware (tried with both the static elf and the .bin). Initially tried using Multifuzz's generated config but that failed due to unmapped reads.

```bash
cargo run --release -- ./FreeRTOS/infinitime/
warning: `/home/ritvik/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
    Finished `release` profile [optimized] target(s) in 0.07s
     Running `target/release/hail-fuzz ./FreeRTOS/infinitime/`
Error running fuzzer: Failed to initialize VM for fuzzing execution, unexpected initial exit: UnhandledException(code=ReadUnmapped, value=0x73720)
callstack:
0x0000037088: <unknown>
0x0000000000: <signal handler>
```

## What I Tried

So, I manually modified the `config.yml` generated by Multifuzz by referring to values from the firmware's source linker scripts. And now, it results in -

```bash
2025-01-19T23:17:53.806973Z ERROR hail_fuzz::monitor: New crash (UnhandledException(code=WritePerm, value=0x0)):
0x000002f746: <unknown>

[     1 s]  103.3k rate= 96582/s ext:1    crash= 58068  (1 unq)  hang= 0   (0 unq)  cov= 5     (8    TB)  in= 2   (0 new)  cycle= 998 (find @0)
[     2 s]  169.2k rate= 65942/s hav:1    crash= 96020  (1 unq)  hang= 0   (0 unq)  cov= 5     (8    TB)  in= 2   (0 new)  cycle= 1633 (find @0)
[     3 s]  231.7k rate= 62427/s ext:1    crash= 133983 (1 unq)  hang= 0   (0 unq)  cov= 5     (8    TB)  in= 2   (0 new)  cycle= 2240 (find @0)
[     4 s]  296.4k rate= 64652/s ext:1    crash= 172015 (1 unq)  hang= 0   (0 unq)  cov= 5     (8    TB)  in= 2   (0 new)  cycle= 2874 (find @0)
[     5 s]  358.9k rate= 62562/s ext:1    crash= 209371 (1 unq)  hang= 0   (0 unq)  cov= 5     (8    TB)  in= 2   (0 new)  cycle= 3482 (find @0)
[     6 s]  423.7k rate= 64734/s ext:1    crash= 245548 (1 unq)  hang= 0   (0 unq)  cov= 5     (8    TB)  in= 2   (0 new)  cycle= 4103 (find @0)
```

and the coverage never increases after this.

This is my config.yml file : 

```yml
interrupt_triggers:
  trigger:
    every_nth_tick: 1024
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_10000130:
    base_addr: 0xfffb000
    permissions: rw-
    size: 0xa000

  irq_ret:
    base_addr: 0xfffff000
    permissions: rwx
    size: 0x1000

  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000

  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10005000

  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x10000

  text:
    base_addr: 0x00000000
    file: pinetime-app-1.14.0.out
    ivt_offset: 0x010000
    permissions: r-x
    size: 0x74000
symbols:
... symbols follow
```

I think I'm missing something trivial here, do let me know if there's something obvious I have to add in the configuration for the fuzzing to work as intended.

**Comment by mchesser** [comment]
I tried to reproduce this and I got something somewhat similar:

```bash
$ ./target/release/hail-fuzz ./targets/InfiniTime/
WARNING: Config file not found. Generating default config at: ./targets/InfiniTime/config.yml
Error running fuzzer: Failed to initialize VM for fuzzing execution, unexpected initial exit: UnhandledException(code=ReadUnmapped, value=0x10000130)
callstack:
0x000002f6a2: SystemInit+0x182
0x000002f689: SystemInit+0x168
0x000002d0aa: Reset_Handler+0x15
```

I was able to fix this by modifying the generated config and adding a region for the NRF specific regions:

```diff
interrupt_triggers:
  trigger:
    every_nth_tick: 1000
    fuzz_mode: fuzzed
memory_map:
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  text:
    is_entry: true
    base_addr: 0x00000000
    permissions: r-x
    size: 0x5b0d0
    file: pinetime-app-1.15.0.out
    file_offset: 0x10000
    file_size: 0x5b0d0
    ivt_offset: 0x0
  data:
    base_addr: 0x0005b0d0
    permissions: rw-
    size: 0x5bc0
    file: pinetime-app-1.15.0.out
    file_offset: 0x70000
    file_size: 0x3b4
  nrf_registers:
    base_addr: 0xf0000000
    permissions: rw-
    size: 0x1000
+
+  ficr_region:
+    base_addr: 0x10000000
+    permissions: rw-
+    size: 0x1000
+  uicr_region:
+    base_addr: 0x10001000
+    permissions: rw-
+    size: 0x1000
+
symbols:
    ...
```

It then appears to immediately get stuck in `nrfx_clock_lfclk_start`:

```
New hang (InstructionLimit: UC_ERR_NO_FUZZ_CONSUMPTION):
0x000002d280: nrfx_clock_lfclk_start+0x34
0x000002d187: nrf_drv_clock_lfclk_request+0x46
0x000002d186: nrf_drv_clock_lfclk_request+0x45
0x000000f872: main+0x15
```

Which I believe is due to missing DWT (Data Watchpoint and Trace Unit) emulation which can be worked around by adding the following:

```diff
...
  uicr_region:
    base_addr: 0x10001000
    permissions: rw-
    size: 0x1000
+  
+handlers:
+  nrfx_clock_lfclk_start: ignore
+
symbols:
...
```

After that there are some false positive crashes that are caused by a misfiring interrupt, which can be worked around by adding:

```
nvic:
  disabled_irqs:
    - 6 # 22:  GPIOTE_IRQHandler
```

**Comment by PwnVerse** [comment]
Thanks alot for the quick response Michael. Im afraid Im using the `1.14` version of the pinetime app. Despite SVDs confirming the FICR region in memory to be the one that you have shared in your response, I'm being greeted with a different fuzzer error - 


```rs
 RUST_BACKTRACE=full cargo run --release -- ./FreeRTOS/infinitime/
warning: `/home/ritvik/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
    Finished `release` profile [optimized] target(s) in 0.07s
     Running `target/release/hail-fuzz ./FreeRTOS/infinitime/`
Error running fuzzer: failed to map: ficr_region at 0x10000000

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: icicle_cortexm::CortexmTarget<icicle_cortexm::mmio::FuzzwareMmioHandler<I>>::fuzzware_init
   2: hail_fuzz::setup_vm
   3: hail_fuzz::Fuzzer::new
   4: std::thread::scoped::scope
   5: hail_fuzz::main
   6: std::sys::backtrace::__rust_begin_short_backtrace
   7: std::rt::lang_start::{{closure}}
   8: std::rt::lang_start_internal
   9: main
  10: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  11: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  12: _start
```

This is my config -

```yml
interrupt_triggers:
  trigger:
    every_nth_tick: 1000
    fuzz_mode: fuzzed

memory_map:
  dynamically_added_crash_region_10000130:
    base_addr: 0xfffb000
    permissions: rw-
    size: 0xa000

  irq_ret:
    base_addr: 0xfffff000
    permissions: rwx
    size: 0x1000

  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000

  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10005000

  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x10000

  text:
    base_addr: 0x00000000
    file: pinetime-app-1.14.0.out
    ivt_offset: 0x010000
    permissions: r-x
    size: 0x74000

  ficr_region:
    base_addr: 0x10000000

  uicr_region:
    base_addr: 0x10001000
    permissions: rw-
    size: 0x1000


symbols:
...
```

Adding the `nrfx_clock_lfclk_start` is asking me for a base address. Removing it causes the above error, which is different from the one you got before the clock handler addition. Do let me know what you think about this, thanks alot!
